### PR TITLE
Port to Typescript

### PR DESCRIPTION
**Pull request by jbcpollak**
This is a complete port of the code to Typescript. While I was doing that, I took the liberty of making some other changes as well which you may or may not agree with, feedback would be welcome.

Here is a quick overview of major changes:

* native code moved from `src/` to `native/`
* native decode_signal / encode_signal renamed decodeSignal / encodeSignal respectively 
* native rawchannel.cc renamed to can.cc because the final output file was `can.node` and I found the mismatch between source and compiled file names confusing - I could just as easily rename both to rawchannel as well.
* Javascript code moved to `src/`
* introduced eslint
* added an .editorconfig file

I reverted the below change because I realized it broke API compatibility with the existing code:

~* Instead of flattening the fields of `desc['value']` into Signal, I kept them as Signal.valueDetails~

I made a few limited changes to the unit tests:
* updating import paths
* renamed decode_signal / encode_signal
* signal.value.sign -> signal.sign

I decided to leave the tests in Javascript as a demonstration of API stability, but would port them to TS for future maintenance.

Let me know what you think, I hope this helps!

### CODE REVIEW

**Comment by sebi2k1** [comment]
Thank you for that change. I followed it closely with the very first change but didn’t had time to deeply look into it and I still need to understand the TypeScript a little more.

**Comment by jbcpollak** [comment]
I have been using this code for a while, but I cannot promise it is 100% API compatible - you may want to consider releasing it as a breaking change.

Some things I think are probably not, but could end up as breaking changes are:
* renaming the native functions - if anyone is calling them directly
* rather than iterating over properties of Javascript objects, this code iterates over actual lists. IMO this makes the code a lot more reliable anyway, but it is a difference between the usage.

I'm doing relatively basic stuff with can, so may not have exercised all the possible usecases you've already supported.

**Comment by sebi2k1** [comment]
Looks like TravisCI dropped support and I need to figure to get it running again. But releasing it as a new major version should at least help to make it more clear.

@juleq what do you think?

**Comment by juleq** [comment]
I am mostly living in embedded land, so no need to convince me of the benefits of explicit typing :).

As a data point: In cantools, one of the contributors has introduced Python type hints and I like the assistance that tools like VS Code and its extensions can provide to programmers on top of that.

I am currently not working on projects using node-can and too busy to provide a review of the changes (or to test them). 

But since a major release is a clean cut and users suffering from breaks can always pin to the prior major, I'd say don't stop the progress. I assume TS is still getting more popular in node these days?

**Comment by sebi2k1** [comment]
Hi @jbcpollak just migrated to Github-Actions to get all the tests up and going again. Do you mind rebasing your pull-requests so it merges with master again and runs the CI tests?

Thank you.

**Comment by sebi2k1** [comment]
The build fails due to:
```
+ mocha@10.1.0
npm ERR! A complete log of this run can be found in:
Error: Process completed with exit code 1.
```

I don't know why that popups up with your PR, but I suppose some dependencies triggered it. According to https://github.com/bahmutov/npm-install/issues/103 it can be resolved by explicitly marking fsevents and optional dependency in package.json:
`"optionalDependencies": { "fsevents": "*" },`

Can you give it a try?

Alternatively I can open a branch for TS and you file the PR against that branch, than I can play with it more easily.

**Comment by jbcpollak** [comment]
Hi, I'll have a new push soon!

**Comment by jbcpollak** [comment]
Hello, I pushed some fixes, note I had to change the workflow.yaml a bit, I hope its accurate. I'll double check. The overall process is pretty similar to before, but I split it up into separate stages for dependencies, compile, lint and testing.

Note `npm ci` is preferred for CI/CD dependency installation and `npm run test` means mocha doesn't need to be globally installed.

**Comment by jbcpollak** [comment]
@sebi2k1 - can you approve the workflow to run (https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)? I think that will make it easier to iterate on any problems.

**Comment by sebi2k1** [comment]
It still fails with the same reason.

```
Run npm ci
npm ERR! fsevents not accessible from chokidar

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-11-06T16_24_49_309Z-debug.log
Error: Process completed with exit code 1.
```

FYI) I just fixed the npmpublish.yml on master to use some tooling to publish only on version changes, this way I can merge you PR to master without publishing it right away.

**Comment by jbcpollak** [comment]
Hi, I suspect the problem here is the node version is too old - I changed the cicd.yaml to upgrade npm which may fix the problem, but I am not sure if maintaining support for Node 12 and 14 will be practical - do you think its important?

I can install node 14.x locally and see if I can get the tests passing here too.

**Comment by jbcpollak** [comment]
ok, I'm pretty sure upgrading npm will fix the problem, I was able to reproduce and verify upgrading fixed it

```
pi@arcmotive2:~/src/arcmotive/node-can $ nodenv shell 14.20.1
pi@arcmotive2:~/src/arcmotive/node-can $ npm --version
6.14.17
pi@arcmotive2:~/src/arcmotive/node-can $ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! fsevents not accessible from chokidar

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-11-06T17_33_19_817Z-debug.log
pi@arcmotive2:~/src/arcmotive/node-can $ npm i -g npm
/home/pi/.nodenv/versions/14.20.1/bin/npm -> /home/pi/.nodenv/versions/14.20.1/lib/node_modules/npm/bin/npm-cli.js
/home/pi/.nodenv/versions/14.20.1/bin/npx -> /home/pi/.nodenv/versions/14.20.1/lib/node_modules/npm/bin/npx-cli.js
+ npm@8.19.3
added 73 packages from 21 contributors, removed 299 packages and updated 138 packages in 27.601s
pi@arcmotive2:~/src/arcmotive/node-can $ npm ci
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

> socketcan@3.0.0 install
> node-gyp rebuild
```

**Comment by jbcpollak** [comment]
Also, I just wanted to mention you might want to use `npm ci` for the `npmpublish` because its possible to introduce subtle differences via `npm install`.

**Comment by sebi2k1** [comment]
> Hi, I suspect the problem here is the node version is too old - I changed the cicd.yaml to upgrade npm which may fix the problem, but I am not sure if maintaining support for Node 12 and 14 will be practical - do you think its important?
> 
> I can install node 14.x locally and see if I can get the tests passing here too.

I did wanted to keep support even for 8.x 🤣 ... well for the CI it might be not important, I just like the way to have it tested against all various NodeJS versions.

Upgrading npm was even a recommendation in the discussion threads.

**Comment by jbcpollak** [comment]
Oops, that's because I removed extra dependencies, I'll fix it.

**Comment by sebi2k1** [comment]
The build for NodeJS 12 failed:
```
/home/runner/work/node-can/node-can/dist/parse_kcd.js:169
[11](https://github.com/sebi2k1/node-can/actions/runs/3405830591/jobs/5664131576#step:8:12)
    const newSignal = new Signal(xmlSignal.name, xmlSignal.spn, bitOffset, parseInt(xmlSignal.length ?? 1), xmlSignal?.endianess ?? "little", labelSet, muxCount, parseFloat(rawValue?.slope ?? 1.0), parseFloat(rawValue?.intercept ?? 0.0), rawValue?.unit ?? "", rawValue?.type ?? "unsigned", parseFloat(rawValue?.defaultValue ?? 0.0), rawValue?.min ? parseFloat(rawValue.min) : undefined, rawValue?.max ? parseFloat(rawValue.max) : undefined);
```

I suppose NodeJS v12 has some issues with TypeScript? If yes, then we have to drop version 12 with the typescript port. Considering it is EOL since mid of 2022 I am not too sorry to kick the support. 👍

**Comment by jbcpollak** [comment]
This is probably tuneable by adjusting the target in tsconfig.json (currently `"target": "ES2021",`), but if you don't mind I'd suggest dropping Node 12 support, its pretty ancient and as you said, EOL.

**Comment by jbcpollak** [comment]
I just pushed a change to drop support for Node 12.x on cicd, I hope that's ok.

Any chance this could get merged soon? It's getting annoying managing links to build my project, hah. :)

**Comment by sebi2k1** [comment]
I will merge it once it passes. We have to clean up a bit (README.md, doc).

**Pull request merged**
